Create a table called user_features_2, based on table order_products_prior, for each user calculate the total number of products, total number of distinct products, and user reorder ratio(number of reordered = 1 divided by number of order_number > 1)

In [1]:
import numpy as np
import pandas as pd

In [2]:
order_products_prior = pd.read_csv('order_products_prior.csv')

In [3]:
order_products_prior

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,eval_set,product_id,add_to_cart_order,reordered
0,2539329,1,1,2,8,0.0,prior,196,1,0
1,2539329,1,1,2,8,0.0,prior,14084,2,0
2,2539329,1,1,2,8,0.0,prior,12427,3,0
3,2539329,1,1,2,8,0.0,prior,26088,4,0
4,2539329,1,1,2,8,0.0,prior,26405,5,0
...,...,...,...,...,...,...,...,...,...,...
13307948,2977660,206209,13,1,12,7.0,prior,39216,4,0
13307949,2977660,206209,13,1,12,7.0,prior,38730,6,0
13307950,2977660,206209,13,1,12,7.0,prior,31477,7,0
13307951,2977660,206209,13,1,12,7.0,prior,6567,8,0
13307952,2977660,206209,13,1,12,7.0,prior,22920,9,0

In [ ]:
user_features_2 = order_products_prior.groupby('user_id').agg(
    sum_product_id = ('product_id', sum),
    sum_distinct_product_id = ('product_id',distinct sum),
    user_reorder_ratio = ('reorder_ratio', )
)

In [ ]:
number of reordered = 1 divided by number of order_number > 1